version: '3.3'
services:
  gitlab:
    image: gitlab/gitlab-ce:${GITLAB_TAG}
    restart: always
    hostname: ${GITLAB_HOSTNAME}
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${GITLAB_HOSTNAME}'
    ports:
    - '80:80'
    - '443:443'
    - '22:22'
    networks: 
      intranet:
        aliases: 
        - ${GITLAB_HOSTNAME}
    volumes:
    - './config:/etc/gitlab'
    - './logs:/var/log/gitlab'
    - './data:/var/opt/gitlab'
  gitlab-runner:
    image: gitlab/gitlab-runner:${RUNNER_TAG}
    restart: always
    depends_on: 
    - gitlab
    - builder
    networks: 
      intranet:
    volumes: 
    - './runner-config:/etc/gitlab-runner'
    - '//var/run/docker.sock:/var/run/docker.sock'
  builder:
    build: ./build-container
    restart: "no"
    command: "echo Built!"
networks: 
  intranet:
    driver: bridge
    name: ${NETWORK_NAME}
